package fitnessclub.interfacelayer;

import fitnessclub.Util;
import fitnessclub.datalayer.DataGateway;
import fitnessclub.entity.Manager;
import fitnessclub.servicelayer.ServiceLayer;

/**
 *
 * @author Lera Rodina
 */
public class ManagerFrame extends javax.swing.JFrame{

    ServiceLayer sl = new ServiceLayer();
    String selectedRow;
    int appstate;
    int clientid;

    public ManagerFrame(Manager m) {
        initComponents();
        
        this.jLabel2.setText(m.getForname() + " " + m.getSurname());
        this.clientDetailsButton.setEnabled(false);
        
        refreshLists();
    }
    
    private void refreshLists(){
        this.ClientsList.setModel(sl.parseAllClients());
        this.StaffList.setModel(sl.parseAllStaff());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managerPane = new javax.swing.JTabbedPane();
        staffPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StaffList = new javax.swing.JList();
        newStaffButton = new javax.swing.JButton();
        clientsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClientsList = new javax.swing.JList();
        clientDetailsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FitnessClub Manager");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        StaffList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(StaffList);

        newStaffButton.setText("New Staff");
        newStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStaffButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout staffPanelLayout = new javax.swing.GroupLayout(staffPanel);
        staffPanel.setLayout(staffPanelLayout);
        staffPanelLayout.setHorizontalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(staffPanelLayout.createSequentialGroup()
                .addComponent(newStaffButton)
                .addGap(0, 148, Short.MAX_VALUE))
        );
        staffPanelLayout.setVerticalGroup(
            staffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(newStaffButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        managerPane.addTab("Staff", staffPanel);

        ClientsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ClientsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientsListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ClientsList);

        clientDetailsButton.setText("Details...");
        clientDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientsPanelLayout = new javax.swing.GroupLayout(clientsPanel);
        clientsPanel.setLayout(clientsPanelLayout);
        clientsPanelLayout.setHorizontalGroup(
            clientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsPanelLayout.createSequentialGroup()
                .addComponent(clientDetailsButton)
                .addGap(0, 152, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        clientsPanelLayout.setVerticalGroup(
            clientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientsPanelLayout.createSequentialGroup()
                .addComponent(clientDetailsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        managerPane.addTab("Clients", clientsPanel);
        clientsPanel.getAccessibleContext().setAccessibleName("ClientsTab");

        jLabel1.setText("Logged in as:");

        jLabel2.setText("unknown");

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managerPane)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(managerPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        managerPane.getAccessibleContext().setAccessibleName("StaffTab");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStaffButtonActionPerformed
        NewStaffFrame nsf = new NewStaffFrame();
        nsf.setVisible(true);
    }//GEN-LAST:event_newStaffButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sl.pl.logOff(Util.currPersonOnline);
        DataGateway.close();
    }//GEN-LAST:event_formWindowClosing

    private void clientDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientDetailsButtonActionPerformed
        switch(appstate){
            case 1:
                DoctorListFrame dlf = new DoctorListFrame(clientid);
                dlf.setVisible(true);
                this.clientDetailsButton.setEnabled(false);
                break;
            case 2:
                this.clientDetailsButton.setEnabled(false);
                break;
            case 3:
                this.clientDetailsButton.setEnabled(false);
                break;
            case 4:
                sl.offerContractToClient(clientid);
                this.clientDetailsButton.setEnabled(false);
                break;
            case 5:
                this.clientDetailsButton.setEnabled(false);
                break;
            case 6:
                sl.approveClientContract(clientid);
                this.clientDetailsButton.setEnabled(false);
                break;
            case 7:
                this.clientDetailsButton.setEnabled(false);
                break;
            case 8:
                this.clientDetailsButton.setEnabled(false);
                break;
            case 9:
                this.clientDetailsButton.setEnabled(false);
                break;
            case 10:
                this.clientDetailsButton.setEnabled(false);
                break;
            case 11:
                this.clientDetailsButton.setEnabled(false);
                break;
            default:
        }
    }//GEN-LAST:event_clientDetailsButtonActionPerformed

    private void ClientsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsListMouseClicked
        selectedRow = ClientsList.getModel().getElementAt(ClientsList.locationToIndex(evt.getPoint())).toString();
        int tmppersonid;
        
        String[] tmpstr = selectedRow.split(" ");
        tmppersonid = Integer.parseInt(tmpstr[0]);
        clientid = sl.cl.getClientId(tmppersonid);
        appstate = sl.checkAppState(tmppersonid);
        
        switch(appstate){
            case 1:
                clientDetailsButton.setText("Assign doctor");
                clientDetailsButton.setEnabled(true);
                break;
            case 2:
                break;
            case 3:
                break;
            case 4:
                clientDetailsButton.setText("Offer contract");
                clientDetailsButton.setEnabled(true);
                break;
            case 5:
                break;
            case 6:
                clientDetailsButton.setText("Approve contract");
                clientDetailsButton.setEnabled(true);
                break;
            case 7:
                break;
            case 8:
                break;
            case 9:
                break;
            case 10:
                break;
            case 11:
                break;
            default:
        }
    }//GEN-LAST:event_ClientsListMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        refreshLists();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ClientsList;
    private javax.swing.JList StaffList;
    private javax.swing.JButton clientDetailsButton;
    private javax.swing.JPanel clientsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane managerPane;
    private javax.swing.JButton newStaffButton;
    private javax.swing.JPanel staffPanel;
    // End of variables declaration//GEN-END:variables
}
